const general = [
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'PLAN A TU MEDIDA<5KW',
    tarifa: '<5KW',
    principal: '55.8',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'PLAN A TU MEDIDA>5KW',
    tarifa: '>5KW',
    principal: '63.8',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'PLAN ESPECIAL<5KW',
    tarifa: '<5KW',
    principal: '40.8',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'PLAN ESPECIAL>5KW',
    tarifa: '>5KW',
    principal: '48.8',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'PLAN EXCLUSIVO <5KW',
    tarifa: '<5KW',
    principal: '48.4',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'PLAN EXCLUSIVO>5KW',
    tarifa: '>5KW',
    principal: '56.4',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS BASICO ',
    tarifa: '3.1',
    principal: '12.8',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS BASICO',
    tarifa: '3.2',
    principal: '12.8',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS IBERDROLA (INCLUYE SMG + FE)',
    tarifa: '3.1',
    principal: '42.4',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS IBERDROLA (INCLUYE SMG + FE)',
    tarifa: '3.2',
    principal: '42.4',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '2.0TD >10kW -15%',
    tarifa: '10 A 15 KW',
    principal: '205',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '2.0TD >10kW - 26%',
    tarifa: '10 A 15 KW',
    principal: '165',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '2.0TD >10kW - 30%',
    tarifa: '10 A 15 KW',
    principal: '110',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '2.0TD >10kW - A TU MEDIDA',
    tarifa: '10 A 15 KW',
    principal: '165',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 15%',
    tarifa: '15 A 20 KW',
    principal: '310',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 15%',
    tarifa: '20 A 50 KW',
    principal: '410',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 15%',
    tarifa: '50 A 100 KW',
    principal: '530',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 15%',
    tarifa: '100 A 150 KW',
    principal: '625',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 15%',
    tarifa: '150 A 250 KW',
    principal: '900',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 15%',
    tarifa: '250 A 450 KW',
    principal: '1400',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 15%',
    tarifa: '> 450 KW',
    principal: '1700',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 26%',
    tarifa: '15 A 20 KW',
    principal: '275',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 26%',
    tarifa: '20 A 50 KW',
    principal: '370',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 26%',
    tarifa: '50 A 100 KW',
    principal: '470',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 26%',
    tarifa: '100 A 150 KW',
    principal: '530',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 26%',
    tarifa: '150 A 250 KW',
    principal: '750',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 26%',
    tarifa: '250 A 450 KW',
    principal: '1000',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 26%',
    tarifa: '> 450 KW',
    principal: '1300',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 30%',
    tarifa: '15 A 20 KW',
    principal: '200',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 30%',
    tarifa: '20 A 50 KW',
    principal: '280',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 30%',
    tarifa: '50 A 100 KW',
    principal: '350',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 30%',
    tarifa: '100 A 150 KW',
    principal: '400',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 30%',
    tarifa: '150 A 250 KW',
    principal: '560',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 30%',
    tarifa: '250 A 450 KW',
    principal: '600',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - 30%',
    tarifa: '> 450 KW',
    principal: '900',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - A TU MEDIDA',
    tarifa: '15 A 20 KW',
    principal: '275',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - A TU MEDIDA',
    tarifa: '20 A 50 KW',
    principal: '370',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - A TU MEDIDA',
    tarifa: '50 A 100 KW',
    principal: '470',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - A TU MEDIDA',
    tarifa: '100 A 150 KW',
    principal: '530',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - A TU MEDIDA',
    tarifa: '150 A 250 KW',
    principal: '750',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - A TU MEDIDA',
    tarifa: '250 A 450 KW',
    principal: '1000',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - A TU MEDIDA',
    tarifa: '> 450 KW',
    principal: '1300',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - EMPRESAS 5%',
    tarifa: '15 A 20 KW',
    principal: '200',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - EMPRESAS 5%',
    tarifa: '20 A 50 KW',
    principal: '280',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - EMPRESAS 5%',
    tarifa: '50 A 80 KW',
    principal: '350',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - EMPRESAS 5%',
    tarifa: '80 A 100 KW',
    principal: '470',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - EMPRESAS 5%',
    tarifa: '100 A 150 KW',
    principal: '530',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - EMPRESAS 5%',
    tarifa: '150 A 250 KW',
    principal: '750',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - EMPRESAS 5%',
    tarifa: '250 A 450 KW',
    principal: '1000',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - EMPRESAS 5%',
    tarifa: '> 450 KW',
    principal: '1300',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - EMPRESAS 10%',
    tarifa: '15 A 20 KW',
    principal: '160',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - EMPRESAS 10%',
    tarifa: '20 A 50 KW',
    principal: '220',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - EMPRESAS 10%',
    tarifa: '50 A 80 KW',
    principal: '280',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - EMPRESAS 10%',
    tarifa: '80 A 100 KW',
    principal: '350',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - EMPRESAS 10%',
    tarifa: '100 A 150 KW',
    principal: '400',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - EMPRESAS 10%',
    tarifa: '150 A 250 KW',
    principal: '560',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - EMPRESAS 10%',
    tarifa: '250 A 450 KW',
    principal: '600',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: '3.0TD - EMPRESAS 10%',
    tarifa: '> 450 KW',
    principal: '900',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - 5%',
    tarifa: '10 A 15 KW',
    principal: '132',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - 5%',
    tarifa: '15 A 20 KW',
    principal: '240',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - 5%',
    tarifa: '20 A 50 KW',
    principal: '336',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - 5%',
    tarifa: '50 A 80 KW',
    principal: '420',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - 5%',
    tarifa: '80 A 100 KW',
    principal: '564',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - 5%',
    tarifa: '100 A 150 KW',
    principal: '636',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - 5%',
    tarifa: '150 A 250 KW',
    principal: '900',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - 5%',
    tarifa: '250 A 450 KW',
    principal: '1200',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - 5%',
    tarifa: '> 450 KW',
    principal: '1560',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - 10%',
    tarifa: '10 A 15 KW',
    principal: '72',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - 10%',
    tarifa: '15 A 20 KW',
    principal: '192',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - 10%',
    tarifa: '20 A 50 KW',
    principal: '264',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - 10%',
    tarifa: '0 A 80 KW',
    principal: '336',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - 10%',
    tarifa: '80 A 100 KW',
    principal: '420',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - 10%',
    tarifa: '100 A 150 KW',
    principal: '480',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - 10%',
    tarifa: '150 A 250 KW',
    principal: '672',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - 10%',
    tarifa: '250 A 450 KW',
    principal: '720',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - 10%',
    tarifa: '> 450 KW',
    principal: '1080',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - Plan Exclusivo 15%',
    tarifa: '10 A 15 KW',
    principal: '246',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - Plan Exclusivo 15%',
    tarifa: '15 A 20 KW',
    principal: '372',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - Plan Exclusivo 15%',
    tarifa: '20 A 50 KW',
    principal: '492',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - Plan Exclusivo 15%',
    tarifa: '50 A 100 KW',
    principal: '636',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - Plan Exclusivo 15%',
    tarifa: '100 A 150 KW',
    principal: '750',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - Plan Exclusivo 15%',
    tarifa: '150 A 250 KW',
    principal: '1080',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - Plan Exclusivo 15%',
    tarifa: '250 A 450 KW',
    principal: '1680',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'ALTA TENSIÓN - Plan Exclusivo 15%',
    tarifa: '> 450 KW',
    principal: '2040',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS L3- 5%',
    tarifa: 'L3',
    principal: '245',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS L4 - 5%',
    tarifa: 'L4 < 300 MWH',
    principal: '700',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS L4 - 5%',
    tarifa: '300<L4>500MWH',
    principal: '840',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS L4 - 5%',
    tarifa: 'L4>500MWH',
    principal: '980',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS L3 - 10%',
    tarifa: 'L3',
    principal: '210',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS L4- 10%',
    tarifa: 'L4 < 300 MWH',
    principal: '350',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS L4- 10%',
    tarifa: '300<L4>500MWH',
    principal: '420',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS L4- 10%',
    tarifa: 'L4>500MWH',
    principal: '700',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS L3 - 12%',
    tarifa: 'L3',
    principal: '125',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS L4 - 12%',
    tarifa: 'L4 < 300 MWH',
    principal: '175',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS L4 - 12%',
    tarifa: '300<L4>500MWH',
    principal: '280',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS L4 - 12%',
    tarifa: 'L4>500MWH',
    principal: '350',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS L3 - 20%',
    tarifa: 'L3',
    principal: '70',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS L4 - 20%',
    tarifa: 'L4 < 300 MWH',
    principal: '85',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS L4 - 20%',
    tarifa: '300<L4>500MWH',
    principal: '150',
  },
  {
    tipologia: 'IBERDROLA_SOLYMAR',
    concepto: 'GAS L4 - 20%',
    tarifa: 'L4>500MWH',
    principal: '200',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '2.0A/DHA',
    tarifa: '0 A 5',
    principal: '70',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '2.0A/DHA',
    tarifa: '5 A 10',
    principal: '80',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '2.0A/DHA',
    tarifa: '> 10',
    principal: '100',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '2.1A/DHA',
    tarifa: '0 A 10 ',
    principal: '200',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '2.1A/DHA',
    tarifa: '10 A 20',
    principal: '250',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '2.1A/DHA',
    tarifa: '20 A 30',
    principal: '380',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '2.1A/DHA',
    tarifa: '30 A 50',
    principal: '415',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '2.1A/DHA',
    tarifa: '> 50',
    principal: '505',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A ESTANDAR',
    tarifa: '0 A 10 ',
    principal: '220',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A ESTANDAR',
    tarifa: '10 A 20',
    principal: '300',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A ESTANDAR',
    tarifa: '20 A 30',
    principal: '425',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A ESTANDAR',
    tarifa: '30 A 50',
    principal: '540',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A ESTANDAR',
    tarifa: '50 A 100',
    principal: '640',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A ESTANDAR',
    tarifa: '100 A 150',
    principal: '795',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A ESTANDAR',
    tarifa: '150 A 200',
    principal: '835',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A ESTANDAR',
    tarifa: '200 A 250',
    principal: '865',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A ESTANDAR',
    tarifa: '> 250',
    principal: '1035',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A MAS',
    tarifa: '0 A 10 ',
    principal: '250',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A MAS',
    tarifa: '10 A 20',
    principal: '350',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A MAS',
    tarifa: '20 A 30',
    principal: '470',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A MAS',
    tarifa: '30 A 50',
    principal: '595',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A MAS',
    tarifa: '50 A 100',
    principal: '690',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A MAS',
    tarifa: '100 A 150',
    principal: '855',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A MAS',
    tarifa: '150 A 200',
    principal: '900',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A MAS',
    tarifa: '200 A 250',
    principal: '935',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A MAS',
    tarifa: '> 250',
    principal: '1130',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A MENOS',
    tarifa: '0 A 10 ',
    principal: '190',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A MENOS',
    tarifa: '10 A 20',
    principal: '255',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A MENOS',
    tarifa: '20 A 30',
    principal: '350',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A MENOS',
    tarifa: '30 A 50',
    principal: '460',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A MENOS',
    tarifa: '50 A 100',
    principal: '535',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A MENOS',
    tarifa: '100 A 150',
    principal: '690',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A MENOS',
    tarifa: '150 A 200',
    principal: '720',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A MENOS',
    tarifa: '200 A 250',
    principal: '750',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.0A MENOS',
    tarifa: '> 250',
    principal: '900',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A ESTANDAR',
    tarifa: '0 A 10 ',
    principal: '200',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A ESTANDAR',
    tarifa: '10 A 20',
    principal: '255',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A ESTANDAR',
    tarifa: '20 A 30',
    principal: '385',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A ESTANDAR',
    tarifa: '30 A 50',
    principal: '505',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A ESTANDAR',
    tarifa: '50 A 100',
    principal: '640',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A ESTANDAR',
    tarifa: '100 A 150',
    principal: '785',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A ESTANDAR',
    tarifa: '150 A 200',
    principal: '805',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A ESTANDAR',
    tarifa: '200 A 250',
    principal: '845',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A ESTANDAR',
    tarifa: '> 250',
    principal: '970',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A MAS',
    tarifa: '0 A 10 ',
    principal: '225',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A MAS',
    tarifa: '10 A 20',
    principal: '295',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A MAS',
    tarifa: '20 A 30',
    principal: '430',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A MAS',
    tarifa: '30 A 50',
    principal: '580',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A MAS',
    tarifa: '50 A 100',
    principal: '730',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A MAS',
    tarifa: '100 A 150',
    principal: '870',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A MAS',
    tarifa: '150 A 200',
    principal: '900',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A MAS',
    tarifa: '200 A 250',
    principal: '940',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A MAS',
    tarifa: '> 250',
    principal: '1090',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A MENOS',
    tarifa: '0 A 10 ',
    principal: '160',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A MENOS',
    tarifa: '10 A 20',
    principal: '205',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A MENOS',
    tarifa: '20 A 30',
    principal: '315',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A MENOS',
    tarifa: '30 A 50',
    principal: '440',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A MENOS',
    tarifa: '50 A 100',
    principal: '550',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A MENOS',
    tarifa: '100 A 150',
    principal: '660',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A MENOS',
    tarifa: '150 A 200',
    principal: '670',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A MENOS',
    tarifa: '200 A 250',
    principal: '700',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1A MENOS',
    tarifa: '> 250',
    principal: '820',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.1 GAS',
    tarifa: '0 A 5',
    principal: '15',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.2 GAS',
    tarifa: '5 A 50',
    principal: '35',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.3 GAS',
    tarifa: '50 A 100',
    principal: '200',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.4 GAS ESTANDAR',
    tarifa: '1 A 150',
    principal: '2',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.4 GAS ESTANDAR',
    tarifa: '150 A 250',
    principal: '2',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.4 GAS ESTANDAR',
    tarifa: '250 A 500',
    principal: '2',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.4 GAS ESTANDAR',
    tarifa: '500 A 1000',
    principal: '2',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.4 GAS ESTANDAR',
    tarifa: '1000 A 2000',
    principal: '2',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.4 GAS ESTANDAR',
    tarifa: '> 2000',
    principal: '2',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.4 GAS MAS',
    tarifa: '1 A 150',
    principal: '3',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.4 GAS MAS',
    tarifa: '150 A 250',
    principal: '3',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.4 GAS MAS',
    tarifa: '250 A 500',
    principal: '3',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.4 GAS MAS',
    tarifa: '500 A 1000',
    principal: '3',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.4 GAS MAS',
    tarifa: '1000 A 2000',
    principal: '3',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.4 GAS MAS',
    tarifa: '> 2000',
    principal: '3',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.4 GAS MENOS',
    tarifa: '1 A 150',
    principal: '1',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.4 GAS MENOS',
    tarifa: '150 A 250',
    principal: '1',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.4 GAS MENOS',
    tarifa: '250 A 500',
    principal: '1',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.4 GAS MENOS',
    tarifa: '500 A 1000',
    principal: '1',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.4 GAS MENOS',
    tarifa: '1000 A 2000',
    principal: '1',
  },
  {
    tipologia: 'ENDESA_SOLYMAR',
    concepto: '3.4 GAS MENOS',
    tarifa: '> 2000',
    principal: '1',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD ONLINE INDEX',
    principal: '50',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD ONLINE+ INDEX',
    principal: '80',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD ONLINE INDEX',
    principal: '150',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD ONLINE+ INDEX',
    principal: '200',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FACIL EXCELLENT +',
    tarifa: '0 A 10 ',
    principal: '80',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FACIL EXCELLENT +',
    tarifa: '> 10',
    principal: '150',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FACIL EXCELLENT',
    tarifa: '0 A 10 ',
    principal: '70',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FACIL EXCELLENT',
    tarifa: '> 10',
    principal: '70',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FACIL PREMIUM +',
    tarifa: '0 A 10 ',
    principal: '60',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FACIL PREMIUM +',
    tarifa: '> 10',
    principal: '60',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FACIL PREMIUM',
    tarifa: '0 A 10 ',
    principal: '31.5',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FACIL PREMIUM',
    tarifa: '> 10',
    principal: '31.5',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS ONLINE',
    tarifa: '3.1/3.2',
    principal: '50',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS ONLINE',
    tarifa: '3.3/3.4',
    principal: '150',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS ONLINE+',
    tarifa: '3.1/3.2',
    principal: '80',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS ONLINE+',
    tarifa: '3.3/3.4',
    principal: '200',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT+',
    tarifa: '0 A 1',
    principal: '80',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT+',
    tarifa: '1 A 2',
    principal: '86',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT+',
    tarifa: '2 A 5',
    principal: '97',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT+',
    tarifa: '5 A 10',
    principal: '165',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT+',
    tarifa: '10 A 20',
    principal: '240',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT+',
    tarifa: '20 A 30 ',
    principal: '515',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT+',
    tarifa: '30 A 40',
    principal: '635',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT+',
    tarifa: '40 A 50',
    principal: '694',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT+',
    tarifa: '50 A 70',
    principal: '925',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT+',
    tarifa: '70 A 100',
    principal: '1230',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT+',
    tarifa: '>100',
    principal: '1900',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT',
    tarifa: '0 A 1',
    principal: '57',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT',
    tarifa: '1 A 2',
    principal: '62',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT',
    tarifa: '2 A 5',
    principal: '67',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT',
    tarifa: '5 A 10',
    principal: '120',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT',
    tarifa: '10 A 20',
    principal: '174',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT',
    tarifa: '20 A 30 ',
    principal: '315',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT',
    tarifa: '30 A 40',
    principal: '394',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT',
    tarifa: '40 A 50',
    principal: '582',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT',
    tarifa: '50 A 70',
    principal: '655',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT',
    tarifa: '70 A 100',
    principal: '830',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA EXCELLENT',
    tarifa: '>100',
    principal: '1270',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM+',
    tarifa: '0 A 1',
    principal: '33',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM+',
    tarifa: '1 A 2',
    principal: '33',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM+',
    tarifa: '2 A 5',
    principal: '54',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM+',
    tarifa: '5 A 10',
    principal: '89',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM+',
    tarifa: '10 A 20',
    principal: '120',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM+',
    tarifa: '20 A 30 ',
    principal: '263',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM+',
    tarifa: '30 A 40',
    principal: '345',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM+',
    tarifa: '40 A 50',
    principal: '463',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM+',
    tarifa: '50 A 70',
    principal: '595',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM+',
    tarifa: '70 A 100',
    principal: '730',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM+',
    tarifa: '>100',
    principal: '1000',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM',
    tarifa: '0 A 1',
    principal: '25',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM',
    tarifa: '1 A 2',
    principal: '25',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM',
    tarifa: '2 A 5',
    principal: '43',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM',
    tarifa: '5 A 10',
    principal: '76',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM',
    tarifa: '10 A 20',
    principal: '100',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM',
    tarifa: '20 A 30 ',
    principal: '218',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM',
    tarifa: '30 A 40',
    principal: '265',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM',
    tarifa: '40 A 50',
    principal: '306',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM',
    tarifa: '50 A 70',
    principal: '390',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM',
    tarifa: '70 A 100',
    principal: '470',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD FIJA PREMIUM',
    tarifa: '>100',
    principal: '600',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT+',
    tarifa: '0 A 5',
    principal: '186',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT+',
    tarifa: '5 A 10',
    principal: '305',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT+',
    tarifa: '10 A 20',
    principal: '350',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT+',
    tarifa: '20 A 30 ',
    principal: '686',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT+',
    tarifa: '30 A 40',
    principal: '910',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT+',
    tarifa: '40 A 50',
    principal: '935',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT+',
    tarifa: '50 A 70',
    principal: '1167',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT+',
    tarifa: '70 A 100',
    principal: '1615',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT+',
    tarifa: '100 A 150',
    principal: '1795',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT+',
    tarifa: '150 A 200',
    principal: '2560',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT+',
    tarifa: '200 A 300',
    principal: '3580',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT+',
    tarifa: '300 A 400',
    principal: '5100',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT+',
    tarifa: '400 A 500',
    principal: '6600',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT+',
    tarifa: '500 A 700',
    principal: '8800',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT+',
    tarifa: '700 A 1.200',
    principal: '12400',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT+',
    tarifa: '1.200 A 2.500',
    principal: '22000',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT+',
    tarifa: '>2.500',
    principal: '35000',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT',
    tarifa: '0 A 5',
    principal: '142',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT',
    tarifa: '5 A 10',
    principal: '218',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT',
    tarifa: '10 A 20',
    principal: '290',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT',
    tarifa: '20 A 30 ',
    principal: '495',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT',
    tarifa: '30 A 40',
    principal: '610',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT',
    tarifa: '40 A 50',
    principal: '660',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT',
    tarifa: '50 A 70',
    principal: '807',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT',
    tarifa: '70 A 100',
    principal: '1155',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT',
    tarifa: '100 A 150',
    principal: '1260',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT',
    tarifa: '150 A 200',
    principal: '1700',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT',
    tarifa: '200 A 300',
    principal: '2380',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT',
    tarifa: '300 A 400',
    principal: '3400',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT',
    tarifa: '400 A 500',
    principal: '4460',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT',
    tarifa: '500 A 700',
    principal: '5880',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT',
    tarifa: '700 A 1.200',
    principal: '8290',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT',
    tarifa: '1.200 A 2.500',
    principal: '14500',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA EXCELLENT',
    tarifa: '>2.500',
    principal: '20000',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM+',
    tarifa: '0 A 5',
    principal: '65',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM+',
    tarifa: '5 A 10',
    principal: '140',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM+',
    tarifa: '10 A 20',
    principal: '195',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM+',
    tarifa: '20 A 30 ',
    principal: '341',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM+',
    tarifa: '30 A 40',
    principal: '404',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM+',
    tarifa: '40 A 50',
    principal: '490',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM+',
    tarifa: '50 A 70',
    principal: '595',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM+',
    tarifa: '70 A 100',
    principal: '815',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM+',
    tarifa: '100 A 150',
    principal: '955',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM+',
    tarifa: '150 A 200',
    principal: '1360',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM+',
    tarifa: '200 A 300',
    principal: '1900',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM+',
    tarifa: '300 A 400',
    principal: '2720',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM+',
    tarifa: '400 A 500',
    principal: '3570',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM+',
    tarifa: '500 A 700',
    principal: '4700',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM+',
    tarifa: '700 A 1.200',
    principal: '6600',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM+',
    tarifa: '1.200 A 2.500',
    principal: '11500',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM+',
    tarifa: '>2.500',
    principal: '15000',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM',
    tarifa: '0 A 5',
    principal: '25',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM',
    tarifa: '5 A 10',
    principal: '70',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM',
    tarifa: '10 A 20',
    principal: '148',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM',
    tarifa: '20 A 30 ',
    principal: '209',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM',
    tarifa: '30 A 40',
    principal: '325',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM',
    tarifa: '40 A 50',
    principal: '350',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM',
    tarifa: '50 A 70',
    principal: '480',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM',
    tarifa: '70 A 100',
    principal: '670',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM',
    tarifa: '100 A 150',
    principal: '835',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM',
    tarifa: '150 A 200',
    principal: '990',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM',
    tarifa: '200 A 300',
    principal: '1195',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM',
    tarifa: '300 A 400',
    principal: '1705',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM',
    tarifa: '400 A 500',
    principal: '2230',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM',
    tarifa: '500 A 700',
    principal: '2940',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM',
    tarifa: '700 A 1.200',
    principal: '4145',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM',
    tarifa: '1.200 A 2.500',
    principal: '7200',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD FIJA PREMIUM',
    tarifa: '>2.500',
    principal: '10500',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'FIJA BASSIC % DEL FEE/2.0TD/3.0TD/6.1TD',
    principal: '0',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT+',
    tarifa: '0 A 1',
    principal: '84',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT+',
    tarifa: '1 A 2',
    principal: '90',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT+',
    tarifa: '2 A 5',
    principal: '102',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT+',
    tarifa: '5 A 10',
    principal: '173',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT+',
    tarifa: '10 A 20',
    principal: '252',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT+',
    tarifa: '20 A 30 ',
    principal: '541',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT+',
    tarifa: '30 A 40',
    principal: '667',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT+',
    tarifa: '40 A 50',
    principal: '729',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT+',
    tarifa: '50 A 70',
    principal: '971',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT+',
    tarifa: '70 A 100',
    principal: '1292',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT+',
    tarifa: '>100',
    principal: '1995',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT',
    tarifa: '0 A 1',
    principal: '60',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT',
    tarifa: '1 A 2',
    principal: '65',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT',
    tarifa: '2 A 5',
    principal: '70',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT',
    tarifa: '5 A 10',
    principal: '126',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT',
    tarifa: '10 A 20',
    principal: '183',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT',
    tarifa: '20 A 30 ',
    principal: '331',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT',
    tarifa: '30 A 40',
    principal: '414',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT',
    tarifa: '40 A 50',
    principal: '611',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT',
    tarifa: '50 A 70',
    principal: '688',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT',
    tarifa: '70 A 100',
    principal: '872',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX EXCELLENT',
    tarifa: '>100',
    principal: '1334',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM+',
    tarifa: '0 A 1',
    principal: '35',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM+',
    tarifa: '1 A 2',
    principal: '35',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM+',
    tarifa: '2 A 5',
    principal: '57',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM+',
    tarifa: '5 A 10',
    principal: '93',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM+',
    tarifa: '10 A 20',
    principal: '126',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM+',
    tarifa: '20 A 30 ',
    principal: '276',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM+',
    tarifa: '30 A 40',
    principal: '362',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM+',
    tarifa: '40 A 50',
    principal: '486',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM+',
    tarifa: '50 A 70',
    principal: '625',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM+',
    tarifa: '70 A 100',
    principal: '767',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM+',
    tarifa: '>100',
    principal: '1050',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM',
    tarifa: '0 A 1',
    principal: '26',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM',
    tarifa: '1 A 2',
    principal: '26',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM',
    tarifa: '2 A 5',
    principal: '45',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM',
    tarifa: '5 A 10',
    principal: '80',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM',
    tarifa: '10 A 20',
    principal: '105',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM',
    tarifa: '20 A 30 ',
    principal: '229',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM',
    tarifa: '30 A 40',
    principal: '278',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM',
    tarifa: '40 A 50',
    principal: '321',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM',
    tarifa: '50 A 70',
    principal: '410',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM',
    tarifa: '70 A 100',
    principal: '494',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '2.0TD INDEX PREMIUM',
    tarifa: '>100',
    principal: '630',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT+',
    tarifa: '0 A 5',
    principal: '195',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT+',
    tarifa: '5 A 10',
    principal: '320',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT+',
    tarifa: '10 A 20',
    principal: '368',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT+',
    tarifa: '20 A 30 ',
    principal: '720',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT+',
    tarifa: '30 A 40',
    principal: '956',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT+',
    tarifa: '40 A 50',
    principal: '982',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT+',
    tarifa: '50 A 70',
    principal: '1225',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT+',
    tarifa: '70 A 100',
    principal: '1696',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT+',
    tarifa: '100 A 150',
    principal: '1885',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT+',
    tarifa: '150 A 200',
    principal: '2688',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT+',
    tarifa: '200 A 300',
    principal: '3759',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT+',
    tarifa: '300 A 400',
    principal: '5355',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT+',
    tarifa: '400 A 500',
    principal: '6930',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT+',
    tarifa: '500 A 700',
    principal: '9240',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT+',
    tarifa: '700 A 1.200',
    principal: '13020',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT+',
    tarifa: '1.200 A 2.500',
    principal: '23100',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT+',
    tarifa: '>2.500',
    principal: '36750',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT',
    tarifa: '0 A 5',
    principal: '149',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT',
    tarifa: '5 A 10',
    principal: '229',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT',
    tarifa: '10 A 20',
    principal: '305',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT',
    tarifa: '20 A 30 ',
    principal: '520',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT',
    tarifa: '30 A 40',
    principal: '641',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT',
    tarifa: '40 A 50',
    principal: '693',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT',
    tarifa: '50 A 70',
    principal: '847',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT',
    tarifa: '70 A 100',
    principal: '1213',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT',
    tarifa: '100 A 150',
    principal: '1323',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT',
    tarifa: '150 A 200',
    principal: '1785',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT',
    tarifa: '200 A 300',
    principal: '2499',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT',
    tarifa: '300 A 400',
    principal: '3570',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT',
    tarifa: '400 A 500',
    principal: '4683',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT',
    tarifa: '500 A 700',
    principal: '6174',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT',
    tarifa: '700 A 1.200',
    principal: '8705',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT',
    tarifa: '1.200 A 2.500',
    principal: '15225',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX EXCELLENT',
    tarifa: '>2.500',
    principal: '21000',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM+',
    tarifa: '0 A 5',
    principal: '68',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM+',
    tarifa: '5 A 10',
    principal: '147',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM+',
    tarifa: '10 A 20',
    principal: '205',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM+',
    tarifa: '20 A 30 ',
    principal: '358',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM+',
    tarifa: '30 A 40',
    principal: '424',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM+',
    tarifa: '40 A 50',
    principal: '515',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM+',
    tarifa: '50 A 70',
    principal: '625',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM+',
    tarifa: '70 A 100',
    principal: '856',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM+',
    tarifa: '100 A 150',
    principal: '1003',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM+',
    tarifa: '150 A 200',
    principal: '1428',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM+',
    tarifa: '200 A 300',
    principal: '1995',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM+',
    tarifa: '300 A 400',
    principal: '2856',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM+',
    tarifa: '400 A 500',
    principal: '3749',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM+',
    tarifa: '500 A 700',
    principal: '4935',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM+',
    tarifa: '700 A 1.200',
    principal: '6930',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM+',
    tarifa: '1.200 A 2.500',
    principal: '12075',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM+',
    tarifa: '>2.500',
    principal: '15750',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM',
    tarifa: '0 A 5',
    principal: '26',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM',
    tarifa: '5 A 10',
    principal: '74',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM',
    tarifa: '10 A 20',
    principal: '155',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM',
    tarifa: '20 A 30 ',
    principal: '219',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM',
    tarifa: '30 A 40',
    principal: '341',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM',
    tarifa: '40 A 50',
    principal: '368',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM',
    tarifa: '50 A 70',
    principal: '504',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM',
    tarifa: '70 A 100',
    principal: '704',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM',
    tarifa: '100 A 150',
    principal: '877',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM',
    tarifa: '150 A 200',
    principal: '1040',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM',
    tarifa: '200 A 300',
    principal: '1255',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM',
    tarifa: '300 A 400',
    principal: '1790',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM',
    tarifa: '400 A 500',
    principal: '2342',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM',
    tarifa: '500 A 700',
    principal: '3087',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM',
    tarifa: '700 A 1.200',
    principal: '4352',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM',
    tarifa: '1.200 A 2.500',
    principal: '7560',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: '3.0TD/6.1TD INDEX PREMIUM',
    tarifa: '>2.500',
    principal: '11025',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'INDEX BASSIC % DEL FEE/2.0TD/3.0TD/6.1TD',
    principal: '0',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.1 EXCELLENT+',
    tarifa: '0 A 1',
    principal: '40',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.1 EXCELLENT+',
    tarifa: '1 A 2',
    principal: '68',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.1 EXCELLENT+',
    tarifa: '2 A 5',
    principal: '85',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.2 EXCELLENT+',
    tarifa: '5 A 10',
    principal: '125',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.2 EXCELLENT+',
    tarifa: '10 A 25',
    principal: '229',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.2 EXCELLENT+',
    tarifa: '25 A 50',
    principal: '473',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.3 EXCELLENT+',
    tarifa: '50 A 75',
    principal: '647',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.3 EXCELLENT+',
    tarifa: '75 A 100',
    principal: '846',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT+',
    tarifa: '100 A 150',
    principal: '1150',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT+',
    tarifa: '150 A 300',
    principal: '1755',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT+',
    tarifa: '300 A 400',
    principal: '2330',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT+',
    tarifa: '400 A 500',
    principal: '3200',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT+',
    tarifa: '500 A 600',
    principal: '3800',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT+',
    tarifa: '600 A 800',
    principal: '4700',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT+',
    tarifa: '800 A 1000',
    principal: '6300',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT+',
    tarifa: '1000 A 2000',
    principal: '9300',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT+',
    tarifa: '2000 A 3000',
    principal: '17000',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT+',
    tarifa: '3000 A 4000',
    principal: '23130',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT+',
    tarifa: '>4000',
    principal: '25800',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.1 EXCELLENT',
    tarifa: '0 A 1',
    principal: '30',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.1 EXCELLENT',
    tarifa: '1 A 2',
    principal: '50',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.1 EXCELLENT',
    tarifa: '2 A 5',
    principal: '60',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.2 EXCELLENT',
    tarifa: '5 A 10',
    principal: '105',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.2 EXCELLENT',
    tarifa: '10 A 25',
    principal: '180',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.2 EXCELLENT',
    tarifa: '25 A 50',
    principal: '375',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.3 EXCELLENT',
    tarifa: '50 A 75',
    principal: '500',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.3 EXCELLENT',
    tarifa: '75 A 100',
    principal: '650',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT',
    tarifa: '100 A 150',
    principal: '880',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT',
    tarifa: '150 A 300',
    principal: '1380',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT',
    tarifa: '300 A 400',
    principal: '1650',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT',
    tarifa: '400 A 500',
    principal: '2250',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT',
    tarifa: '500 A 600',
    principal: '2700',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT',
    tarifa: '600 A 800',
    principal: '3500',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT',
    tarifa: '800 A 1000',
    principal: '4400',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT',
    tarifa: '1000 A 2000',
    principal: '6600',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT',
    tarifa: '2000 A 3000',
    principal: '12200',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT',
    tarifa: '3000 A 4000',
    principal: '15500',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 EXCELLENT',
    tarifa: '>4000',
    principal: '20000',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.1 PREMIUM +',
    tarifa: '0 A 1',
    principal: '18',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.1 PREMIUM +',
    tarifa: '1 A 2',
    principal: '30',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.1 PREMIUM +',
    tarifa: '2 A 5',
    principal: '45',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.2 PREMIUM +',
    tarifa: '5 A 10',
    principal: '81',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.2 PREMIUM +',
    tarifa: '10 A 25',
    principal: '140',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.2 PREMIUM +',
    tarifa: '25 A 50',
    principal: '287',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.3 PREMIUM +',
    tarifa: '50 A 75',
    principal: '425',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.3 PREMIUM +',
    tarifa: '75 A 100',
    principal: '580',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM +',
    tarifa: '100 A 150',
    principal: '650',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM +',
    tarifa: '150 A 300',
    principal: '1000',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM +',
    tarifa: '300 A 400',
    principal: '1450',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM +',
    tarifa: '400 A 500',
    principal: '1950',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM +',
    tarifa: '500 A 600',
    principal: '2300',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM +',
    tarifa: '600 A 800',
    principal: '2800',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM +',
    tarifa: '800 A 1000',
    principal: '3900',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM +',
    tarifa: '1000 A 2000',
    principal: '5900',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM +',
    tarifa: '2000 A 3000',
    principal: '10900',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM +',
    tarifa: '3000 A 4000',
    principal: '14800',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM +',
    tarifa: '>4000',
    principal: '17500',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.1 PREMIUM',
    tarifa: '0 A 1',
    principal: '5',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.1 PREMIUM',
    tarifa: '1 A 2',
    principal: '25',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.1 PREMIUM',
    tarifa: '2 A 5',
    principal: '37',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.2 PREMIUM',
    tarifa: '5 A 10',
    principal: '46',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.2 PREMIUM',
    tarifa: '10 A 25',
    principal: '80',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.2 PREMIUM',
    tarifa: '25 A 50',
    principal: '155',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.3 PREMIUM',
    tarifa: '50 A 75',
    principal: '290',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.3 PREMIUM',
    tarifa: '75 A 100',
    principal: '400',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM',
    tarifa: '100 A 150',
    principal: '400',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM',
    tarifa: '150 A 300',
    principal: '720',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM',
    tarifa: '300 A 400',
    principal: '1050',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM',
    tarifa: '400 A 500',
    principal: '1350',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM',
    tarifa: '500 A 600',
    principal: '1650',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM',
    tarifa: '600 A 800',
    principal: '2080',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM',
    tarifa: '800 A 1000',
    principal: '2660',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM',
    tarifa: '1000 A 2000',
    principal: '3950',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM',
    tarifa: '2000 A 3000',
    principal: '7300',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM',
    tarifa: '3000 A 4000',
    principal: '10100',
  },
  {
    tipologia: 'ALDRO_SOLYMAR',
    concepto: 'GAS 3.4 PREMIUM',
    tarifa: '>4000',
    principal: '14000',
  },

];
export default general;
